language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: jdJ7KE3AHIp1GB8Ol/foVys4WJ50gWJnT9WeULyks8i+DcnOBWbwcpF5ikp/L5TahxmMmp7y/mjhFR6oXdvYVVtLxJfyvt22Jc8Hzjj7PL6SgF10j6r6DZoCZWu9ZDHpPc2+KyMsP4PgsKBrSNBh5tK76SxTZ86bJZGAYVDw+6q64GNQ5zsvh1XvN9gUv0u/T6Z0ZF3mYZCbbq0ge77k7tYqw9HWmKUbn8isM7A0nKv2eLPMoGVMR0u+/MKpSfYLA3SnUY6IgCMBfC47KlSTfXNIJunTcjJsoBfvY1PRGNNVEBVXsKbSTb6HLFAumBvJdP3TztKCucdjDs6AC4gkgfUV/3LlRm057TVjwzed6g21h4ZVsryiKB5r1XS7gUwsfGJf1p/Ia8W1Lg8C3mBKbS3wUTEYrUJSVuKdB3FEislgXcFwqAG1n1U4ifj0elrbQR9DZCxMU0dm8KmLQWHiNx3r1zZs+0Cq8aTq7wsLgcSNMzv1fiw6FXK+YOFSAcVY1o2uikJnDj+ZiPv6T9RPfGOm7oK17z410gAeNNfYx8WthWzqJejtCQyf/0Ba6aIjgY/4M1oHi3zA3OJPDfAi/tOAg7obo9s+SLj6WW2uQ/uIZ7A14LB4WLE0hwzBAT9q5vQloZTf8m3x2jzkBR6SBuzxz5RTv0ga268hsgOLdKM=
